/**
 * Visual identity for a niche tile: an icon and a hue.
 *
 * The niche catalog is a plain list of names (see NICHE_CATALOG in
 * routes/dashboard.leads.tsx), so tiles are drawn, not photographed — an icon
 * on a tinted surface keeps ~80 tiles consistent and costs no image bytes.
 * Anything not listed (a future catalog addition) falls back to a neutral
 * storefront icon, so adding a niche never needs a change here to render.
 */
import {
  Activity,
  BookOpen,
  Bed,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  Code2,
  Coffee,
  Croissant,
  Droplets,
  Dumbbell,
  Eye,
  Factory,
  Flower2,
  Gem,
  Globe,
  GraduationCap,
  Hammer,
  HardHat,
  Handshake,
  Heart,
  HeartPulse,
  Home,
  Key,
  Laptop,
  Leaf,
  Megaphone,
  Music,
  Newspaper,
  Package,
  Palette,
  PawPrint,
  PenTool,
  Plane,
  Printer,
  Receipt,
  Rocket,
  Ruler,
  Scale,
  Scissors,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sofa,
  Sparkles,
  Stethoscope,
  Store,
  Trophy,
  TreePine,
  TrendingUp,
  Truck,
  Users,
  Utensils,
  UtensilsCrossed,
  Video,
  Waves,
  Wind,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "Accounting Firm": Calculator,
  "Advertising Agency": Megaphone,
  "Architecture Studio": Ruler,
  "Auto Dealership": Car,
  "Auto Repair": Wrench,
  "Bakery": Croissant,
  "Beauty Salon": Sparkles,
  "Branding Studio": PenTool,
  "Catering Company": UtensilsCrossed,
  "Chiropractic Clinic": Activity,
  "Coffee Shop": Coffee,
  "Construction Company": HardHat,
  "Consulting Firm": Briefcase,
  "Coworking Space": Users,
  "Dental Clinic": Smile,
  "E-commerce": ShoppingCart,
  "Education Center": GraduationCap,
  "Event Planning": Calendar,
  "Financial Advisor": TrendingUp,
  "Fitness Studio": Dumbbell,
  "Florist": Flower2,
  "Food Truck": Truck,
  "Freelance Designer": Palette,
  "Funeral Home": Leaf,
  "Gym": Dumbbell,
  "Hair Salon": Scissors,
  "Health Clinic": HeartPulse,
  "Home Improvement": Hammer,
  "Hotel": Bed,
  "HR Consulting": Handshake,
  "HVAC Company": Wind,
  "Insurance Agency": Shield,
  "Interior Design Studio": Sofa,
  "IT Services": Laptop,
  "Jewelry Store": Gem,
  "Landscaping": TreePine,
  "Law Firm": Scale,
  "Local Services": Store,
  "Logistics Company": Package,
  "Manufacturing": Factory,
  "Marketing Agency": Megaphone,
  "Medical Clinic": Stethoscope,
  "Mortgage Broker": Key,
  "Moving Company": Package,
  "Music School": Music,
  "Non-profit": Heart,
  "Optometry Clinic": Eye,
  "Personal Trainer": Trophy,
  "Pet Services": PawPrint,
  "Photography Studio": Camera,
  "Physical Therapy": Activity,
  "Plumbing": Droplets,
  "Print Shop": Printer,
  "Property Management": Building2,
  "Psychotherapy Practice": Brain,
  "Public Relations": Newspaper,
  "Real Estate": Home,
  "Recruitment Agency": Users,
  "Repair Services": Wrench,
  "Restaurant": Utensils,
  "Retail": ShoppingBag,
  "Roofing": Home,
  "SaaS Founders": Rocket,
  "Security Company": Shield,
  "Software Agency": Code2,
  "Spa & Wellness": Waves,
  "Sports Club": Trophy,
  "Tax Services": Receipt,
  "Travel Agency": Plane,
  "Tutoring": BookOpen,
  "Veterinary Clinic": PawPrint,
  "Video Production": Video,
  "Web Design Agency": Globe,
  "Wedding Planner": Heart,
  "Yoga Studio": Leaf,
};

export function nicheIcon(name: string): LucideIcon {
  return ICONS[name] ?? Store;
}

/** Stable hue (indigo → violet → blue) so neighbouring tiles differ a little
 * without leaving the MAST palette. Deterministic: the same niche always
 * gets the same tint. */
export function nicheHue(name: string): number {
  let h = 0;
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0;
  return 240 + (h % 7) * 9; // 240 … 294
}
