// Precomputed Natural Earth 110m Country Discovery Data
// 14 Focus Countries: ISO-3166-1 alpha-3, exact land point membership, opportunity counts & city hubs

export type FocusCountry = {
  iso: string;
  name: string;
  lat: number;
  lon: number;
  zoom: number;
  opportunities: number;
};

export const FOCUS_COUNTRIES: FocusCountry[] = [
  {
    "iso": "USA",
    "name": "United States",
    "lat": 38.5,
    "lon": -97,
    "zoom": 1.08,
    "opportunities": 4820
  },
  {
    "iso": "BRA",
    "name": "Brazil",
    "lat": -14.2,
    "lon": -51.9,
    "zoom": 1.1,
    "opportunities": 1290
  },
  {
    "iso": "AUS",
    "name": "Australia",
    "lat": -25.3,
    "lon": 134.5,
    "zoom": 1.1,
    "opportunities": 980
  },
  {
    "iso": "EGY",
    "name": "Egypt",
    "lat": 26.5,
    "lon": 30,
    "zoom": 1.16,
    "opportunities": 640
  },
  {
    "iso": "FRA",
    "name": "France",
    "lat": 46.5,
    "lon": 2.5,
    "zoom": 1.16,
    "opportunities": 1420
  },
  {
    "iso": "DEU",
    "name": "Germany",
    "lat": 51.2,
    "lon": 10.4,
    "zoom": 1.16,
    "opportunities": 1840
  },
  {
    "iso": "RUS",
    "name": "Russia",
    "lat": 58,
    "lon": 80,
    "zoom": 1.07,
    "opportunities": 1650
  },
  {
    "iso": "CAN",
    "name": "Canada",
    "lat": 56,
    "lon": -100,
    "zoom": 1.08,
    "opportunities": 1120
  },
  {
    "iso": "ZAF",
    "name": "South Africa",
    "lat": -29,
    "lon": 24.5,
    "zoom": 1.15,
    "opportunities": 780
  },
  {
    "iso": "ARG",
    "name": "Argentina",
    "lat": -35,
    "lon": -65,
    "zoom": 1.12,
    "opportunities": 590
  },
  {
    "iso": "CHN",
    "name": "China",
    "lat": 35,
    "lon": 104,
    "zoom": 1.08,
    "opportunities": 3950
  },
  {
    "iso": "JPN",
    "name": "Japan",
    "lat": 36.5,
    "lon": 138,
    "zoom": 1.18,
    "opportunities": 2150
  },
  {
    "iso": "NGA",
    "name": "Nigeria",
    "lat": 9.5,
    "lon": 8,
    "zoom": 1.16,
    "opportunities": 860
  },
  {
    "iso": "NZL",
    "name": "New Zealand",
    "lat": -41.5,
    "lon": 173,
    "zoom": 1.18,
    "opportunities": 340
  }
];

// Packed Int8 country membership: (cIdx + 1) per dot, where 0 = none, 1..14 = country index + 1
const PACKED_COUNTRY_DATA = "AAAACAAHAAAHBwAHCAAIAAcABwcABwgABwAHCAAHAAcIBwgABwcIAAcIBwAHCAcABwcIBwAHCAcHCAcABwcIAQcIAAcHAAcHBwEHBwAHBwAHCAAHBwEHCAAHCAcIBwEHBwcHCAcIBwAHCAAHBwEHCAcABwgHCAcBBwAHBwEHCAAHCAAHCAcBBwgHBwAHCAcIBwcIAAcHAQcIBwAHCAcHAQcIBwcHCAcIBwcHCAAHBwEHCAcABwgHBwEHCAAHBwEHCAcHBwgABwgHAQAHCAcHAAcIBwgHBwgHBwEHCAcABwgHBwEHCAAHBwgHBwcIAAcIBwEHCAcHAAcIBwcHCAAHBwEHCAcHCAAHBwEHCAcHBwgHBwcIBwcBBwgHAAcIAAcIBwEHCAAHBwEHBwcIAAcHAQcIBwcHCAcHBwgABwcBBwgHBwgABwgHAQcIBwcHCAcHBwgHBwgHBwgABwcBBwgHBwEHBwcIAAcIBwEHCAcHCAcHBwgIBwcIBwcIAAgHAQcIBwcHBwcIAAgHAQcIBwcBBwcHCAcHBwgHBwgACAcHCAcHBwcHCAgHBwgHBwgHBwgABwAHCAcHCAAIBwcIBwcHBwgABwgHBwgHBwgACAcHCAcHBwgHBwgIBwcIBwcHBwgABwcIBwcICAcHCAcHCAcHCAcIBwcIBwcICAcHCAAHBwgHBwgIAAcIBwcHBwgACAAABwgHBwgGCAAHCAAHAAcIBwcIAAgACwgHBwAHBwgACAcABwgHBwgGCAAHCAcHAAcIBwcIAAgABwgHBwYIAAcIAAgHAAcIBwcIAAgACwgHBwAIBwcIAAgABwgHBwgGCAAHCAAHAAcIAAcIAAgACwgHBwYIBwcIAAAHCAcACAAIAAsIAAcFBwgABwgAAAsIBwAGCAAACAAABwgAAAgAAAsIAAAFBwgABwgAAAcIBwAIBggACwEAAAUHCAAAAQAACwEHAAYIAAABAAgABQcIAAABAAALAQALBQgAAAEAAAsBBwAGCAAAAQAIAAUHAQAAAQAIAAsBAAUIAAABAAALAQcAAQAIAAsBAAsFCAAAAQAIAAsBBwAACAAAAQAABwEAAAEAAQALAQsFCAAAAQAACwEHAAAIAAsBCwUBAAABAAALAQcLAAgACwEACwcBAAABAAEACwELBQgAAAEAAAsBBwAAAQALAQsBAAABAAALAQsFDAgAAAEAAAALAQcAAQABAAsBCwUBAAABAAALAQALAQALAQsAAQALAQALAQsIAAsBAAAAAAEACwEACwELAAEACwEACwELAQALAQALAAEACwEAAAsBAAsBAAsBAAAAAQALAQALAQALAAEACwEAAAsBAAsBAAsBCwABAAsACwEACwEACwEAAAABAAsBAAsBAAsAAQALAQABAAsMAQALAQsAAQALAAsBAAsAAQALAQABAAsBAAsBCwABAAsAAQALAQALAQAAAAEACwALAQALAAEACwEACwEACwEACwELAAEACwALAQALDAEACwEAAQALAAEACwELAAEACwALAQsADAEACwEAAAEACwAACwELAQALAQABAAsAAQALAQAAAQALAAsBAAsADAEACwEAAQALAAALAQsADAEACwABAAsAAQALAQABAAsACwELAAEACwABAAsAAAsBCwABAAsACwELAAEACwEAAQALAAALAQsAAQALAAEACwAACwEAAAEACwAACwELAAEACwAAAQALAAALAQsAAQALAAALAQALAAEACwAAAAEACwAACwAECwABAAsAAQALAAALAAQAAAEACwAACwEECwABAAsAAAEACwAACwAEAAALAAALAQALAAALAAAAAAsAAAsABAsAAAsAAAEACwAACwAEAAAACwAACwALAAALAAAAAAAAAAsABAAACwAAAQAAAAALBAAAAAAAAAsABAAAAAsAAAAAAAAACwAEAAAACwAAAAAAAQsAAAAAAAAACwAEAAALAAAAAQAAAAALBAAAAAsAAAsABAAACwAAAAAAAAALAAQAAAALAAAAAAALAAAAAAAACwAEAAALAAAAAAAACwQAAAALAAAABAAAAAsAAAAAAAALBAAAAAsAAAAAAAAACwQAAAAAAAAEAAAACwAAAAAAAAsEAAAACwAAAAAAAAALAAAAAAAABAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAADQAAAAANAAAAAAAAAA0AAAAAAA0AAAAADQAAAAAAAAAADQAAAAAAAAAAAAAAAA0AAAAAAAAADQAAAAANAAAAAAAAAAAAAA0AAAAAAAANAAAAAA0AAAAAAAANAAAAAAAAAAAAAAAADQAAAAAAAAANAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAABQAAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAABQAAAAAAAAAAAAACAAAAAAAFAAAAAAAAAAAAAAIAAgAAAAACAAACAAAAAgAAAAAAAgAAAAAAAAACAAAAAAACAAAAAAACAAACAAAAAAIAAAACAAIAAAAAAgAAAAIAAgACAAAAAAIAAAIAAgAAAAIAAAACAAIAAAACAAACAAIAAAIAAAACAAAAAgACAAAAAgAAAAACAAACAgAAAAIAAAACAAIAAAACAgAAAAIAAAICAAACAAIAAgAAAAICAAACAAICAAAAAgIAAgACAAAAAgIAAAACAgACAAIAAAACAgACAAIAAgIAAAACAgACAAIAAAACAgAAAgACAAIAAAAAAgIAAgAAAgACAAIAAAACAgACAAIAAAICAgACAAIAAgAAAgIAAgAAAgACAgAAAgAAAAIAAgIAAAIAAgIAAAIAAAACAAICAAACAAAAAgACAgAAAAIAAgIAAAIDAAAAAAIDAAICAAACAAAAAgACAwAAAAIAAAIAAAIDAAAAAgMAAgMCAAAAAgAAAwIAAgMAAAAAAgMAAAMCAAACAwAAAwACAwACAwAAAAACAAADAAIAAgMAAAMAAgMAAAMAAgAAAgMAAAMAAgMAAgMAAAAAAgMAAAMCAAIDAAADAgMAAAMAAAACAwAAAwIDAAIDAAADAgMAAAMAAgACAwAAAwIDAAIDAAAAAwIDAAADAgMAAgMAAAMCAwAAAwADAAIDAAADAgMAAAIDAAADAgMAAAMAAwMAAgMACgMCAwAAAwAAAwACAwAKAwMDCQIDAAADAgMAAAMAAwMAAgMACgMDCQADAAADAgMACgMDAwkCAwAKAwMJCgMDAwIDAAoDAwMJAAMACgMDCQoDAwMAAgMACgMDCQADAwADAgMJCgMDAwkCAwAKAwMJCgMDAwIDCQoDAwAKAwMKAwMJCgMDAwIDCQoDAwkKAwMAAwIDCQoDAwkCAwoDAwkKAwMDAgMJCgMDCQADAwoDAwkKAwADCQoDAwkKAwADAwkKAwAKAwMKAwMJCgMAAwoDCgMKAAoDCgoDCgMKAwoACgMKCgAKCgoKDgoDCg4ACgoOCgAOCgAOCgoACgAACgoAAAAA";

// Packed UInt8 opportunity/city density: 0..255 per dot
const PACKED_DENSITY_DATA = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXwAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAwAAAAAAAAAAAAAAuAAAAADEAAAAAAAAAKQAAAAAAIAAAAKUAAAAEAAAAAAAAOwAAAABuAAAAtR8AMwAAAAADAAAAXgAAAFgAAAAAAAB7AAAAAHUAAItTABIAAAAAAACTAACuAB0AUQAAAIEAAAAAPQAAjlVCAD0AAAAAAACfAAAAAK0AFjmgAABEAAgAAAAA9CJ7AG4ASwAAoQAAAFUAAGeeAAIAWgAAAAAAogAAAHoAYACVAABRAAAAAAAAm00oAK0AAAAAAABjAADMAAAAIACYAAAAAAA/AAAAAAB7AAArAJQAAEcAAAAyADvsAAAAADdNAAAAAACBAAAAAAAoAKIAAAA/AABPAAAAAABYAAAAAAArAAAAAAC2AAAAAAAAAGmuAAAAAAAlAAAAAABrAAAAAAAAANsAAABrAAAAAAAArwAAAAAAAAC1AAAAAKcAAAAAAADEFAAADwAAAAAAAH4AAAAAAACSAAQAAHUAAAAAAAC3sjwAAAAAAMMAAAAALgAAAAAAALhOAAAAAAAAGgAAAAC5AAAAAAAAvxUAAAAAAAAAAADUiwAAAAAAAG0AAAAAaQAAAAAAAIlmAAAAAAAAAAAApgCBAAAAAACFLwAACAAAAAAAAAAAtQAAAAAAOiEAAHoAHgAAAADUkAAAAAAAAAAAAADRAAAAALUzAAAfAAAAAAAAAJ4AAAAAAIRMAABRAG4AAAAAlZAAAAAAAAAAAAAAUgAjAACEAAAWAAAAAADHjPUAAAAAAAAARwAADwCuAD0AALRaAAAAAAAAAAAAcABHAAAAsgAAAAAOAACdAAAAAAAAABYAALUAkgAAAKUAAAAAAAAAYQA4AAAAAHoAAEEAAG0AAAA3AAAAAAAAAAAAzwCyAAAAAKcAAE0AAAUAAABnAAAAAAAnAAAAxwAAAFUAAAwAAAAAAADGAHQAAAAAXQAAowAAAABENgAAAAAAAAAAAMAAAAAARQAAYwAAAACeABoAAAAJAAAAAAAAAAAAHAAAAAAAAABlAAAAABAAAK0AAAAAAEcAAAAAAAAAAABcAAAAkgAAAGoAKgAAAG8ABQAAAAAAAAAFAAAA5wAAAEkAADwAAAAAHAAAAAAAkQA7AAAAIgAAAAAABAAAAAUAAAAAtAAADqYAgQAAAAAiAAAAoAAACQAgAAAAAAAAOQBXAAAAMAAAAAAASwCRAAAAADUAAAAAAAAAbgAAAAAAPnkApwAAAAB2AAAAAABjAFUAAAAAHAAAAD4AAAAAVQAAAAAAkQAAqQAAAACMAAAAAABDAADNBgAAAAAAPQAAAJAAAAAAnwDGAAAAALgAWAAAAABXAEIAADwAAQAAnACOAAAAAIQAALcAAAAAtwCcAABsAACuAwAAAAAOAAAAAAAAAGYAzgAAAJUAAGwAAAAAZABEAAAAGAAAiwAAAAA5AAAAAAAAAGoAkQAAWAAAFwAAAAAOAAAAAAAAAEEAZQAAAD4AAAAAAAAAOAAxAAAACQAAAAAAkQAAAAAAAAAAGgBGAAAaAAAACgAAAABCAAAAAAAAAAwABAAAAAAAAAAAAABwAAIAAAAAAAAAAAArAAAAAAAANgAAAAAAAAAAAAAApAAAAAAAAAAAAAAAAAAAAAAAAACWAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAN4AAAAAAAAAAAAAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIAAAAAAAAAXgAAAAAAAAAAAAAAAM0AAAAAABYAAAAASwAAAAAAAAAAigAAAAAAAAAAAAAAAIEAAAAAAAAAaQAAAAAGAAAAAAAAAAAAAMEAAAAAAAB4AAAAAEEAAAAAAACnAAAAAAAAAAAAAAAAigAAAAAAAACxAAAAAAAAAAAAAAAAAIkAAAAAAAAAAAAAAAAAAAAAAAAAAACNAAAAAAAAAAAAAACDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAAAAAAAAAAAAAAAAngAAAAAAAAAAAAAAAAAAAAAAAABOAAAAAAAAAAAAAGwAAAAAAAAAAAAAAAAAFQAAAAAAAAAAPQAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAXAAAAAAAAAAAAAD8AAAAAAAAABAAAAAAAAAAAAGUAAAAAAAAAAAAAAAAMAABOAAAAAAAAFwAArAAAABIAABAAAAAAAAAAAFYAAACJAAAAAAAALwAAAAAAAGcAADYAAAAAAAAAhwAAAAB+AAAAOwAAACAAAAAAAAAAuwAAAAA2AAAAAAAAAABxAAAAAAAAAABvAAAAADYAAAAAAAAAnwAAAAAADwAAFwAAAAAAZwAAAAAAAAAAagAAAABSAAAAAAAAXwAAAAAAAAAYAAAAAKQAAAAAAAAAMAAAAAAAPgAAAAAAAJsAAAAAAAAAAB4AAAAAfgAAAAAAAACAAAAAAAAAAA8AAAAArgAAAAAAAAAAgAAAAAAAAAAAAQAAAADHAAAAAAAAAABgAAAAAAAAXgAAAAAAzAAAAAAAFQAASwAAAAAApQAAAAAAsQAAAAAAAGwRAAAAAACdAABsAIAAAAAAAADOAAAAAAAATQAARAAAMQAADAAAvgAAvQAAbwAAIgAAHXoAAAAXAABbAwBtJiYAAF4AAAAAAJAqAAAASQAYZwAAHm8AACs4AFYAQAAHDZ0AAJIAAG4AAAB9AGSRAC5mugAAPQAAgJYtQCCSWgA1roQADgCczQBjenyEIQCqAFifpGjGTUwAnFZPVGSmAAimiCtXRGAAwVwAAKkADQAAAAAAvAA3ALYAAAC6AAB9AAAuAAAAAAAAAAAAAAAA";

function unpackCountryData(): { countryIds: Int8Array; densities: Float32Array } {
  if (typeof atob === "undefined") {
    return { countryIds: new Int8Array(0), densities: new Float32Array(0) };
  }
  const cBin = atob(PACKED_COUNTRY_DATA);
  const dBin = atob(PACKED_DENSITY_DATA);
  const len = cBin.length;
  const countryIds = new Int8Array(len);
  const densities = new Float32Array(len);

  for (let i = 0; i < len; i++) {
    const rawVal = cBin.charCodeAt(i);
    countryIds[i] = rawVal === 0 ? -1 : (rawVal - 1);
    densities[i] = dBin.charCodeAt(i) / 255;
  }
  return { countryIds, densities };
}

const unpacked = unpackCountryData();
export const DOT_COUNTRY_IDS: Int8Array = unpacked.countryIds;
export const DOT_OPPORTUNITY_DENSITIES: Float32Array = unpacked.densities;
