import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { channelsSatisfied } from "../channelFilter.js";

/**
 * Regression test — Node/Python `instagram` channel schema mismatch.
 *
 * PRODUCTION FINDING: Python Qualification (workers/qualification_worker.py)
 * passed all 4 required channels (email/phone/instagram/website) for 50
 * candidates — `candidate_qualified` -> storage outcome=success ->
 * YIELDED_TO_NODE -> NODE_RECEIVED — and every one of them was then
 * REJECTED here with `channel_filter:["email","phone","instagram","website"]`.
 *
 * Root cause: `service._opportunity_to_lead_dict` (mast-lead-engine/service.py)
 * only ever read `instagram_intel.profile_url` when building the flat lead
 * dict streamed to Node, ignoring the other two sources
 * QualificationWorker's own "instagram" required-channel rule already
 * accepts (`business.instagram_url` and `contact_intel.instagram_url` — see
 * that file's `_resolve_instagram_url` for the fix and full trace).
 *
 * This file does NOT hand-type an approximation of the Python engine's
 * output. `fixtures/pythonEngineLeadPayload.json` is generated by actually
 * running `service._opportunity_to_lead_dict` against a real
 * `QualifiedOpportunity` (see
 * mast-lead-engine/tests/test_node_instagram_schema_mismatch.py's
 * `TestActualLeadPayloadFixtureForNode`) — the exact same dict shape
 * `pythonBridge.ts` parses off stdout and casts `as EngineLead` with no
 * field renaming. Regenerate the fixture by running:
 *
 *     cd mast-lead-engine && pytest tests/test_node_instagram_schema_mismatch.py
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixturePath = path.join(__dirname, "fixtures", "pythonEngineLeadPayload.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf-8")) as {
  qualifiedAllFourChannels: Record<string, unknown>;
  missingInstagram: Record<string, unknown>;
};

const REQUESTED_CHANNELS = ["email", "phone", "instagram", "website"];

test("a lead with website + email + phone + Instagram (Instagram supplied only via ContactWorker discovery, matching Python Qualification's own source) passes channelsSatisfied end-to-end using the real engine payload shape", () => {
  const lead = fixture.qualifiedAllFourChannels;

  // Sanity: this fixture actually represents the production scenario —
  // Instagram present, everything else present too.
  assert.equal(typeof lead.instagram, "string");
  assert.ok((lead.instagram as string).length > 0);
  assert.equal(lead.email, "hello@bakery.com");
  assert.equal(lead.phone, "+14165550199");
  assert.equal(lead.website, "https://bakery.com");

  assert.equal(
    channelsSatisfied(lead as any, REQUESTED_CHANNELS),
    true,
    "a lead qualified by Python for all 4 channels must also pass Node's channelsSatisfied — this is the exact production regression",
  );
});

test("a lead with Instagram genuinely absent still fails channelsSatisfied using the real engine payload shape", () => {
  const lead = fixture.missingInstagram;

  assert.equal(lead.instagram, null);
  // Every other channel is still present, isolating the failure to
  // Instagram specifically (AND semantics — one missing channel fails
  // the whole requirement).
  assert.equal(lead.email, "hello@bakery.com");
  assert.equal(lead.phone, "+14165550199");
  assert.equal(lead.website, "https://bakery.com");

  assert.equal(
    channelsSatisfied(lead as any, REQUESTED_CHANNELS),
    false,
    "a lead with no Instagram source anywhere must still be rejected — this fix must not weaken the channel filter",
  );
});
